
# Base image with Python
FROM python:3.12-slim


WORKDIR /app


COPY requirements.txt .


RUN pip install --upgrade pip && pip install -r requirements.txt


COPY . .


EXPOSE 8009


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8009"]